In [1]:
import pandas as pd

In [8]:
SHEET_URL =  "https://docs.google.com/spreadsheets/d/e/2PACX-1vS8wYLuPNQKJ_pEnDgVl7olGzwNV762wVYAhxubQwtc5xXrWOaha12Ll_YrmvTTIbLwnaZ4UrL1Ukq1/pub?gid=0&single=true&output=csv"
df = pd.read_csv(SHEET_URL, skiprows=4)
df.head(2)

,Factura,Año,Fecha Emision MM DD AAAA,Fecha de Reconocimiento Contable,Mes,FS_,Concepto,Cliente,unidad de negocio,Valor bruto,...,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51
0,FVLU-1,2020.0,17/12/2020,17/12/2020,12.0,NaN,Piloto Tunja Lucro,Alpina Productos Alimenticios S.A,Lucro App,29273915.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FVLU-2,2020.0,17/12/2020,17/12/2020,12.0,NaN,Piloto Tunja Lucro,Alpina Productos Alimenticios S.A,Lucro App,29273915.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# Eliminando columnas con nombres en nulo
df = df.loc[:, ~df.columns.str.startswith("Unnamed")]
df.head(2)

,Factura,Año,Fecha Emision MM DD AAAA,Fecha de Reconocimiento Contable,Mes,FS_,Concepto,Cliente,unidad de negocio,Valor bruto,...,OTROS,Total Descuentos,fecha de pago,Valor pagado,Saldo,Factura anulada solo por efectos de cambio de fecha sin implicacion contable ni tributaria,factura electronica Generada solo por efectos de cambio de fecha sin implicacion contable ni tributaria,Traslado IVA,Fecha esperada de pago,Valor A recibir sin iva
0,FVLU-1,2020.0,17/12/2020,17/12/2020,12.0,NaN,Piloto Tunja Lucro,Alpina Productos Alimenticios S.A,Lucro App,29273915.0,...,0.0,2005263.178,18/12/2020,32830695.67,0.0,NaN,NaN,NaN,NaN,NaN
1,FVLU-2,2020.0,17/12/2020,17/12/2020,12.0,NaN,Piloto Tunja Lucro,Alpina Productos Alimenticios S.A,Lucro App,29273915.0,...,0.0,2005263.178,18/12/2020,32830695.67,0.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Eliminando filas con valores nulos en la factura
df.dropna(axis=0, subset=["Factura"])

,Factura,Año,Fecha Emision MM DD AAAA,Fecha de Reconocimiento Contable,Mes,FS_,Concepto,Cliente,unidad de negocio,Valor bruto,...,OTROS,Total Descuentos,fecha de pago,Valor pagado,Saldo,Factura anulada solo por efectos de cambio de fecha sin implicacion contable ni tributaria,factura electronica Generada solo por efectos de cambio de fecha sin implicacion contable ni tributaria,Traslado IVA,Fecha esperada de pago,Valor A recibir sin iva
0,FVLU-1,2020.0,17/12/2020,17/12/2020,12.0,NaN,Piloto Tunja Lucro,Alpina Productos Alimenticios S.A,Lucro App,29273915.0,...,0.0,2005263.178,18/12/2020,32830695.67,0.00,NaN,NaN,NaN,NaN,NaN
1,FVLU-2,2020.0,17/12/2020,17/12/2020,12.0,NaN,Piloto Tunja Lucro,Alpina Productos Alimenticios S.A,Lucro App,29273915.0,...,0.0,2005263.178,18/12/2020,32830695.67,0.00,NaN,NaN,NaN,NaN,NaN
2,FVLU-3,2021.0,6/6/2021,6/6/2021,6.0,NaN,Entendimiento quesito antioquia,Alpina Productos Alimenticios S.A,Lucro App,14987654.0,...,0.0,1026654.299,3/9/2021,16808653.96,0.00,NaN,NaN,NaN,NaN,NaN
3,FVLU-4,2021.0,7/7/2021,7/7/2021,7.0,NaN,Alimento humedo perros y gatos,Contegral SAS,Lucro App,21000000.0,...,0.0,2908500.000,7/9/2021,22081500.00,0.00,NaN,NaN,NaN,NaN,NaN
4,FVLU-5,2021.0,11/8/2021,11/8/2021,8.0,NaN,FEE junio Al punto,Alpina Productos Alimenticios S.A,Lucro Inside,5850306.0,...,0.0,457259.917,11/10/2021,32523022.00,0.00,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,FVLU-399,2026.0,14/4/2026,31/3/2026,4.0,FS-,Entrenamiento 3 SKU Marzo,Alpina Productos Alimenticios S.A,Lucro App,417000.0,...,0.0,32591.880,NaN,NaN,463638.12,NaN,NaN,79230.00,14/5/2026,NaN
427,FVLU-400,2026.0,14/4/2026,31/3/2026,4.0,FS-,Reconocimiento de imágenes marzo,Alpina Productos Alimenticios S.A,Lucro App,46212300.0,...,0.0,3611952.528,NaN,NaN,51380684.47,NaN,NaN,8780337.00,14/5/2026,NaN
428,FVLU-401,2026.0,14/4/2026,31/3/2026,4.0,FS-,Consumo TAT Marzo,Postobon SA,NaN,80039895.0,...,NaN,5482732.808,NaN,NaN,89764742.24,NaN,NaN,15207580.05,14/5/2026,74557162.19
429,FVLU-402,2026.0,16/4/2026,31/3/2026,4.0,FS-,Consumo AU Marzo,Postobon SA,NaN,2437520.0,...,NaN,166970.120,NaN,NaN,2733678.68,NaN,NaN,463128.80,16/5/2026,2270549.88
430,FVLU-403,2026.0,16/4/2026,16/4/2026,4.0,FS-,BI embajadores,Postobon SA,NaN,11000000.0,...,NaN,753500.000,NaN,NaN,12336500.00,NaN,NaN,2090000.00,16/5/2026,10246500.00

In [ ]:

# Eliminando espacios al comienzo y al final de cada columna 
df.columns = df.columns.str.strip()
df.columns

Index(['Factura', 'Año', 'Fecha Emision  MM DD AAAA',
       'Fecha de Reconocimiento Contable', 'Mes', 'FS_', 'Concepto', 'Cliente',
       'unidad de negocio', 'Valor bruto', 'IVA', 'Valor Total', 'RTE FTE',
       'ICA', 'RTE IVA', 'OTROS', 'Total Descuentos', 'fecha de pago',
       'Valor pagado', 'Saldo',
       'Factura anulada solo por efectos de cambio de fecha sin implicacion contable ni tributaria',
       'factura electronica Generada solo por efectos de cambio de fecha sin implicacion contable ni tributaria',
       'Traslado IVA', 'Fecha esperada de pago', 'Valor A recibir sin iva'],
      dtype='object')

In [ ]:
# Reemplazando valores en cliente

df["Cliente"] = (df["Cliente"]
                 .str.replace(" Ltda", "", regex=False)
                 .str.replace(" S.A", "", regex = False)
                 .str.replace(" SAS", "", regex = False)
                 .str.replace(" SA", "", regex = False)
                 .str.replace(" sas", "", regex = False)
                 .str.replace(" Sas", "", regex = False)
                 .str.replace(".S", "", regex = False)
                 .str.replace(".", "", regex = False))

In [23]:
df["Cliente"] = df["Cliente"].str.strip()

In [25]:
df["Cliente"].unique()

array(['Alpina Productos Alimenticios', 'Contegral',
       'Adbid Latinoamerica', 'BEU INC', 'Colegios Colombianos',
       'Coca Cola bebidas de Colombia', 'Alianza Estrategica CO',
       'Caja de Compensacion Familiar CaFAM', 'Preferente MP',
       'Por el planeta', 'Carvajal educacion', 'Preveo',
       'Operadora Avicola Colombia', 'Rios Barrero Diego Alejandro',
       'Katla Group', 'Organización Radial Olimpica', 'Postobon',
       'Compañia Nacional De Levaduras Levapan',
       'Mms Comunicaciones Colombia', 'Interpublic Colombia',
       'Pepsicola Colombia', 'Casa Luker', 'Brandconnection',
       'Comestibles Ricos', 'Mizooco', 'Biblo Market',
       'Central Cervecera de Colombia', 'Comercial + Bios',
       'Embotelladoras Bepensa', 'Clouxter', 'Deeploy',
       'Nutrimenti de colombia', 'Belleza Express',
       'Propimex S de RL de CV', 'Totales', nan], dtype=object)

In [32]:
mapa = {
    "Alpina Productos Alimenticios": "Alpina",
    "Postobon": "Postobon",
    "Pepsicola Colombia": "Pepsi",
    "Contegral": "Grupo Bios",
    "Caja de Compensacion Familiar CaFAM": "CAFAM",
    "Coca Cola bebidas de Colombia": "Coca-Cola",
    "Compañia Nacional De Levaduras Levapan": "Levapan",
    "Belleza Express": "Bivien",
    "Embotelladoras Bepensa": "Bepensa"
}

In [33]:
df["Cliente Ajustado"] =  df["Cliente"].map(mapa).fillna(df["Cliente"])

In [34]:
df["Cliente Ajustado"].unique()

array(['Alpina', 'Grupo Bios', 'Adbid Latinoamerica', 'BEU INC',
       'Colegios Colombianos', 'Coca-Cola', 'Alianza Estrategica CO',
       'CAFAM', 'Preferente MP', 'Por el planeta', 'Carvajal educacion',
       'Preveo', 'Operadora Avicola Colombia',
       'Rios Barrero Diego Alejandro', 'Katla Group',
       'Organización Radial Olimpica', 'Postobon', 'Levapan',
       'Mms Comunicaciones Colombia', 'Interpublic Colombia', 'Pepsi',
       'Casa Luker', 'Brandconnection', 'Comestibles Ricos', 'Mizooco',
       'Biblo Market', 'Central Cervecera de Colombia',
       'Comercial + Bios', 'Bepensa', 'Clouxter', 'Deeploy',
       'Nutrimenti de colombia', 'Bivien', 'Propimex S de RL de CV',
       'Totales', nan], dtype=object)

In [37]:
# Ver filas donde Cliente es 'Totales' o NaN
df = df[~df["Cliente"].isin(["Totales"])]
df = df.dropna(subset=["Cliente"])
df[df["Cliente"].isin(["Totales"]) | df["Cliente"].isna()]

Empty DataFrame
Columns: [Factura, Año, Fecha Emision  MM DD AAAA, Fecha de Reconocimiento Contable, Mes, FS_, Concepto, Cliente, unidad de negocio, Valor bruto, IVA, Valor Total, RTE FTE, ICA, RTE IVA, OTROS, Total Descuentos, fecha de pago, Valor pagado, Saldo, Factura anulada solo por efectos de cambio de fecha sin implicacion contable ni tributaria, factura electronica Generada solo por efectos de cambio de fecha sin implicacion contable ni tributaria, Traslado IVA, Fecha esperada de pago, Valor A recibir sin iva, Cliente Ajustado]
Index: []

[0 rows x 26 columns]